### ISSUE TITLE
Seeking advice on issues encountered during data generation？

### ISSUE THREAD

**Issue by zuowanbushiwo** [JusperLee/SonicSim#3]
python -m habitat_sim.utils.datasets_download --uids mp3d_example_scene --data-path data/
python: Relink `/home/yang/miniconda3/envs/whisperx/lib/python3.10/site-packages/habitat_sim-0.2.2-py3.10-linux-x86_64.egg/habitat_sim/_ext/libRLRAudioPropagation.so' with `/lib/x86_64-linux-gnu/libz.so.1' for IFUNC symbol `crc32_z'
free(): invalid pointer
Aborted (core dumped)

Thanks！

**Comment by JusperLee** [comment]
https://github.com/facebookresearch/rlr-audio-propagation/issues/9#issuecomment-1317697962
